INSERT INTO regiones (id, nombre) VALUES (1, 'Norteamérica');
INSERT INTO regiones (id, nombre) VALUES (2, 'Centroamérica');
INSERT INTO regiones (id, nombre) VALUES (3, 'Sudamérica');
INSERT INTO regiones (id, nombre) VALUES (4, 'Europa');
INSERT INTO regiones (id, nombre) VALUES (5, 'Asia');
INSERT INTO regiones (id, nombre) VALUES (6, 'Africa');
INSERT INTO regiones (id, nombre) VALUES (7, 'Oceanía');
INSERT INTO regiones (id, nombre) VALUES (8, 'Antártida');

INSERT INTO `clientes` (id, region_id, nombre, apellido, correo, fecha) VALUES (1, 1, 'Dennis', 'Ritchie','dritchie@gmail.com', '2023-03-01');
INSERT INTO `clientes` (id, region_id, nombre, apellido, correo, fecha) VALUES (2, 1, 'Bjarne', 'Stroustrup', 'bstroustrup@gmail.com', '2023-03-01');
INSERT INTO `clientes` (id, region_id, nombre, apellido, correo, fecha) VALUES (3, 1, 'James', 'Gosling', 'jgosling@gmail.com', '2023-03-01');
INSERT INTO `clientes` (id, region_id, nombre, apellido, correo, fecha) VALUES (4, 1, 'Anders', 'Hejlsberg', 'ahejlsberg@gmail.com', '2023-03-01');
INSERT INTO `clientes` (id, region_id, nombre, apellido, correo, fecha) VALUES (5, 4, 'Guido', 'Van Rossum', 'gvrossum@gmail.com', '2023-03-01');
INSERT INTO `clientes` (id, region_id, nombre, apellido, correo, fecha) VALUES (6, 4, 'Rasmus', 'Lerdof', 'rlerdorf@gmail.com', '2023-03-01');
INSERT INTO `clientes` (id, region_id, nombre, apellido, correo, fecha) VALUES (7, 1, 'Brendan', 'Eich', 'beich@gmail.com', '2023-03-01');
INSERT INTO `clientes` (id, region_id, nombre, apellido, correo, fecha) VALUES (8, 5, 'Yukihiro', 'Matsumoto', 'ymatsumoto@gmail.com', '2023-03-01');
INSERT INTO `clientes` (id, region_id, nombre, apellido, correo, fecha) VALUES (9, 4, 'Linus', 'Torvals', 'ltorvals@gmail.com', '2023-03-01');
INSERT INTO `clientes` (id, region_id, nombre, apellido, correo, fecha) VALUES (10, 1, 'Frederik', 'Kottler', 'fdxdesarrollos@gmail.com', '2023-03-01');
INSERT INTO `clientes` (id, region_id, nombre, apellido, correo, fecha) VALUES (11, 7, 'John', 'Doe', 'john.doe@gmail.com', '2023-03-05');
INSERT INTO `clientes` (id, region_id, nombre, apellido, correo, fecha) VALUES (12, 3, 'Andrés José', 'Guzmán', 'ajguzman@gmail.com', '2023-03-05');
